substitutions:
  name: growatt-mtl
  external_components_source: .
  tx_pin: D8
  rx_pin: D7
  fault_pin: D1
  comms_pin: D2

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  min_version: 2024.6.0

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false

api:
  reboot_timeout: 0s

uart:
  id: uart_0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

growatt_mtl:
  uart_id: uart_0
  id: growatt0
  fault_pin: ${fault_pin}
  comms_pin: ${comms_pin}
text_sensor:
  - platform: growatt_mtl
    growatt_mtl_id: growatt0
    manufacturer:
      name: "${name} model description"
    firmware_version:
      name: "${name} firmware version"
    serial_number:
      name: "${name} serial number"
